'use strict';

/**
 * hwType -> model metadata, generated by scripts/build-tag-models.js from the
 * per-model drivers. Regenerate that script rather than editing this by hand.
 *
 * The AP already tells us the hwType of every tag, so this only supplies the
 * things the AP does not: a human readable model name and the battery layout
 * Homey wants for its energy screen.
 */

const TAG_MODELS = {
  0: { name: "Solum 1.54", batteries: ["CR2450"] }, // 0x00 - legacy driver: solum-154
  1: { name: "Solum 2.9", batteries: ["CR2450","CR2450"] }, // 0x01 - legacy driver: solum-29
  2: { name: "Solum 4.2", batteries: ["CR2450","CR2450"] }, // 0x02 - legacy driver: solum-42
  3: { name: "M2 2.2\"", batteries: ["CR2450","CR2450"] }, // 0x03 - legacy driver: m2-2-2-03
  4: { name: "M2 2.6\"", batteries: ["CR2450","CR2450"] }, // 0x04 - legacy driver: m2-2-6-04
  5: { name: "m2-74", batteries: ["CR2450","CR2450"] }, // 0x05 - legacy driver: m2-74
  6: { name: "Opticon 2.2\"", batteries: ["CR2450","CR2450"] }, // 0x06 - legacy driver: opticon-2-2-06
  7: { name: "Opticon 2.9\"", batteries: ["CR2450","CR2450"] }, // 0x07 - legacy driver: opticon-2-9-07
  8: { name: "Opticon 4.2\"", batteries: ["CR2450","CR2450"] }, // 0x08 - legacy driver: opticon-4-2-08
  9: { name: "Opticon 7.5\"", batteries: ["CR2450","CR2450"] }, // 0x09 - legacy driver: opticon-7-5-09
  17: { name: "M2 2.9\" (UC8151)", batteries: ["CR2450","CR2450"] }, // 0x11 - legacy driver: m2-29-uc8151
  18: { name: "M2 4.2\" UC", batteries: ["CR2450","CR2450"] }, // 0x12 - legacy driver: m2-4-2-uc-12
  33: { name: "ST-GM29XXF 2.9\"", batteries: ["CR2450","CR2450"] }, // 0x21 - legacy driver: st-gm29xxf-2-9-21
  34: { name: "M2 2.7\"", batteries: ["CR2450","CR2450"] }, // 0x22 - legacy driver: m2-2-7-22
  38: { name: "M2 7.5\" BW", batteries: ["CR2450","CR2450"] }, // 0x26 - legacy driver: m2-7-5-bw-26
  39: { name: "ST-GM29MT1 2.9\"", batteries: ["CR2450","CR2450"] }, // 0x27 - legacy driver: st-gm29mt1-2-9-27
  40: { name: "M3 1.6\" BWRY", batteries: ["CR2450"] }, // 0x28 - legacy driver: m3-1-6-bwry-28
  41: { name: "M3 2.4\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x29 - legacy driver: m3-2-4-bwry-29
  42: { name: "M3 3.0\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x2A - legacy driver: m3-3-0-bwry-2a
  43: { name: "M3 2.9\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x2B - legacy driver: m3-2-9-bwry-2b
  44: { name: "M3 4.3\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x2C - legacy driver: m3-4-3-bwry-2c
  45: { name: "M3 12.2\"", batteries: ["CR2450","CR2450"] }, // 0x2D - legacy driver: m3-12-2-2d
  46: { name: "M3 9.7\"", batteries: ["CR2450","CR2450"] }, // 0x2E - legacy driver: m3-9-7-2e
  47: { name: "M3 4.3\"", batteries: ["CR2450","CR2450"] }, // 0x2F - legacy driver: m3-4-3-2f
  48: { name: "M3 1.6\"", batteries: ["CR2450"] }, // 0x30 - legacy driver: m3-1-6-30
  49: { name: "M3 2.2\"", batteries: ["CR2450","CR2450"] }, // 0x31 - legacy driver: m3-2-2-31
  50: { name: "M3 2.6\"", batteries: ["CR2450","CR2450"] }, // 0x32 - legacy driver: m3-2-6-32
  51: { name: "Newton M3 2.9", batteries: ["CR2450","CR2450"] }, // 0x33 - legacy driver: newton-m3-29
  52: { name: "M3 4.2\"", batteries: ["CR2450","CR2450"] }, // 0x34 - legacy driver: m3-4-2-34
  53: { name: "M3 6.0\"", batteries: ["CR2450","CR2450"] }, // 0x35 - legacy driver: m3-6-0-35
  54: { name: "M3 7.5\"", batteries: ["CR2450","CR2450"] }, // 0x36 - legacy driver: m3-7-5-36
  55: { name: "M3 11.6\"", batteries: ["CR2450","CR2450"] }, // 0x37 - legacy driver: m3-11-6-37
  56: { name: "M3 8.2\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x38 - legacy driver: m3-8-2-bwry-38
  60: { name: "M3 4.2\" BWY", batteries: ["CR2450","CR2450"] }, // 0x3C - legacy driver: m3-4-2-bwy-3c
  64: { name: "M3 2.9\" BW", batteries: ["CR2450","CR2450"] }, // 0x40 - legacy driver: m3-2-9-bw-40
  65: { name: "M3 5.85\"", batteries: ["CR2450","CR2450"] }, // 0x41 - legacy driver: m3-5-85-41
  66: { name: "M3 5.85\" BW", batteries: ["CR2450","CR2450"] }, // 0x42 - legacy driver: m3-5-85-bw-42
  67: { name: "M3 1.3\" Peghook", batteries: ["CR2450"] }, // 0x43 - legacy driver: m3-1-3-peghook-43
  68: { name: "M3 5.81\" BW", batteries: ["CR2450","CR2450"] }, // 0x44 - legacy driver: m3-5-81-bw-44
  69: { name: "M3 2.2 Lite\"", batteries: ["CR2450","CR2450"] }, // 0x45 - legacy driver: m3-2-2-lite-45
  70: { name: "M3 2.2\" BW", batteries: ["CR2450","CR2450"] }, // 0x46 - legacy driver: m3-2-2-bw-46
  71: { name: "M3 2.7\"", batteries: ["CR2450","CR2450"] }, // 0x47 - legacy driver: m3-2-7-47
  72: { name: "M3 5.81\" BWR", batteries: ["CR2450","CR2450"] }, // 0x48 - legacy driver: m3-5-81-bwr-48
  73: { name: "M3 5.81\" V2 BWR", batteries: ["CR2450","CR2450"] }, // 0x49 - legacy driver: m3-5-81-v2-bwr-49
  74: { name: "M3 1.6\" 200px BWRY (4A)", batteries: ["CR2450"] }, // 0x4A - legacy driver: m3-1-6-200px-bwry-4a
  75: { name: "M3 2.2\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x4B - legacy driver: m3-2-2-bwry-4b
  76: { name: "M3 7.5\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x4C - legacy driver: m3-7-5-bwry-4c
  77: { name: "M3 11.6\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x4D - legacy driver: m3-11-6-bwry-4d
  78: { name: "M3 2.6\" BW", batteries: ["CR2450","CR2450"] }, // 0x4E - legacy driver: m3-2-6-bw-4e
  79: { name: "M3 2.6\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x4F - legacy driver: m3-2-6-bwry-4f
  80: { name: "HD150 5.83\" BWR", batteries: ["CR2450","CR2450"] }, // 0x50 - legacy driver: hd150-5-83-bwr-50
  83: { name: "M3 3.5\" BWRY RTL", batteries: ["CR2450","CR2450"] }, // 0x53 - legacy driver: m3-3-5-bwry-rtl-53
  84: { name: "HS BW 2.13\"", batteries: ["CR2450","CR2450"] }, // 0x54 - legacy driver: hs-bw-2-13-54
  85: { name: "HS BWR 2.13\"", batteries: ["CR2450","CR2450"] }, // 0x55 - legacy driver: hs-bwr-2-13-55
  86: { name: "HS BWR 2.66\"", batteries: ["CR2450","CR2450"] }, // 0x56 - legacy driver: hs-bwr-2-66-56
  87: { name: "TLSR BWR 1.54\"", batteries: ["CR2450"] }, // 0x57 - legacy driver: tlsr-bwr-1-54-57
  88: { name: "TLSR BW 2.13\" (58)", batteries: ["CR2450","CR2450"] }, // 0x58 - legacy driver: tlsr-bw-2-13-58
  89: { name: "TLSR BWR 2.13\"", batteries: ["CR2450","CR2450"] }, // 0x59 - legacy driver: tlsr-bwr-2-13-59
  90: { name: "HS BW 2.13\" LowRes", batteries: ["CR2450","CR2450"] }, // 0x5A - legacy driver: hs-bw-2-13-lowres-5a
  96: { name: "HS BWY 3.5\"", batteries: ["CR2450","CR2450"] }, // 0x60 - legacy driver: hs-bwy-3-5-60
  97: { name: "HS BWR 3.5\"", batteries: ["CR2450","CR2450"] }, // 0x61 - legacy driver: hs-bwr-3-5-61
  98: { name: "HS BW 3.5\"", batteries: ["CR2450","CR2450"] }, // 0x62 - legacy driver: hs-bw-3-5-62
  99: { name: "TLSR BWR 4.2\"", batteries: ["CR2450","CR2450"] }, // 0x63 - legacy driver: tlsr-bwr-4-2-63
  102: { name: "HS BWY 7,5\"", batteries: ["CR2450","CR2450"] }, // 0x66 - legacy driver: hs-bwy-7-5-66
  103: { name: "HS 2.00\" BWY", batteries: ["CR2450"] }, // 0x67 - legacy driver: hs-2-00-bwy-67
  104: { name: "HS BWY 3.46\"", batteries: ["CR2450","CR2450"] }, // 0x68 - legacy driver: hs-bwy-3-46-68
  105: { name: "TLSR BW 2.13\" (69)", batteries: ["CR2450","CR2450"] }, // 0x69 - legacy driver: tlsr-bw-2-13-69
  106: { name: "HS BWR 5,83\"", batteries: ["CR2450","CR2450"] }, // 0x6A - legacy driver: hs-bwr-5-83-6a
  107: { name: "HS BWRY 7,5\"", batteries: ["CR2450","CR2450"] }, // 0x6B - legacy driver: hs-bwry-7-5-6b
  108: { name: "HS BWRY 2,00\"", batteries: ["CR2450"] }, // 0x6C - legacy driver: hs-bwry-2-00-6c
  109: { name: "HS BWRY 3,5\"", batteries: ["CR2450","CR2450"] }, // 0x6D - legacy driver: hs-bwry-3-5-6d
  110: { name: "HS BWRY 2,9\"", batteries: ["CR2450","CR2450"] }, // 0x6E - legacy driver: hs-bwry-2-9-6e
  111: { name: "HS BWRY 2,60\"", batteries: ["CR2450","CR2450"] }, // 0x6F - legacy driver: hs-bwry-2-60-6f
  112: { name: "HS 2.9\" HighRes", batteries: ["CR2450","CR2450"] }, // 0x70 - legacy driver: hs-2-9-highres-70
  113: { name: "HS 2.13\" BWR High Res", batteries: ["CR2450","CR2450"] }, // 0x71 - legacy driver: hs-2-13-bwr-high-res-71
  128: { name: "Chroma 7.4\"", batteries: ["CR2450","CR2450"] }, // 0x80 - legacy driver: chroma-7-4-80
  129: { name: "Chroma Aeon 74 7.4\"", batteries: ["CR2450","CR2450"] }, // 0x81 - legacy driver: chroma-aeon-74-7-4-81
  130: { name: "Chroma29 2.9\"", batteries: ["CR2450","CR2450"] }, // 0x82 - legacy driver: chroma29-2-9-82
  131: { name: "Chroma42 4.2\"", batteries: ["CR2450","CR2450"] }, // 0x83 - legacy driver: chroma42-4-2-83
  144: { name: "M3 4.2\" BWRY", batteries: ["CR2450","CR2450"] }, // 0x90 - legacy driver: m3-4-2-bwry-90
  145: { name: "M3 1.6\" 200px BWRY (91)", batteries: ["CR2450"] }, // 0x91 - legacy driver: m3-1-6-200px-bwry-91
  176: { name: "Gicisky BLE EPD BW 2.13\"", batteries: ["CR2450","CR2450"] }, // 0xB0 - legacy driver: gicisky-ble-epd-bw-2-13-b0
  177: { name: "Gicisky BLE EPD BWR 2.13\"", batteries: ["CR2450","CR2450"] }, // 0xB1 - legacy driver: gicisky-ble-epd-bwr-2-13-b1
  178: { name: "Gicisky BLE EPD BW 2.9\"", batteries: ["CR2450","CR2450"] }, // 0xB2 - legacy driver: gicisky-ble-epd-bw-2-9-b2
  179: { name: "Gicisky BLE EPD BWR 2.9\"", batteries: ["CR2450","CR2450"] }, // 0xB3 - legacy driver: gicisky-ble-epd-bwr-2-9-b3
  181: { name: "Gicisky BLE EPD BWR 4.2\"", batteries: ["CR2450","CR2450"] }, // 0xB5 - legacy driver: gicisky-ble-epd-bwr-4-2-b5
  186: { name: "Gicisky BLE TFT 2.13\"", batteries: ["CR2450","CR2450"] }, // 0xBA - legacy driver: gicisky-ble-tft-2-13-ba
  189: { name: "BLE EPD BWR 2.9\" Silabs", batteries: ["CR2450","CR2450"] }, // 0xBD - legacy driver: ble-epd-bwr-2-9-silabs-bd
  192: { name: "BWRY example", batteries: ["CR2450","CR2450"] }, // 0xC0 - legacy driver: bwry-example-c0
  193: { name: "ACeP 4.01", batteries: ["CR2450","CR2450"] }, // 0xC1 - legacy driver: acep-4-01-c1
  194: { name: "Spectra 7.3", batteries: ["CR2450","CR2450"] }, // 0xC2 - legacy driver: spectra-7-3-c2
  224: { name: "TFT 320x172", batteries: ["CR2450","CR2450"] }, // 0xE0 - legacy driver: tft-320x172-e0
  225: { name: "TFT 160x80", batteries: ["CR2450"] }, // 0xE1 - legacy driver: tft-160x80-e1
  226: { name: "LILYGO TPANEL 4\"", batteries: ["CR2450","CR2450"] }, // 0xE2 - legacy driver: lilygo-tpanel-4-e2
  227: { name: "GDEM1085Z51 10.85\"", batteries: ["CR2450","CR2450"] }, // 0xE3 - legacy driver: gdem1085z51-10-85-e3
  228: { name: "BLE TFT 128x128", batteries: ["CR2450"] }, // 0xE4 - legacy driver: ble-tft-128x128-e4
  229: { name: "TFT 240x320", batteries: ["CR2450","CR2450"] }, // 0xE5 - legacy driver: tft-240x320-e5
};

/** Model name for a hwType, falling back to something readable. */
function modelName(hwType) {
  const model = TAG_MODELS[hwType];
  if (model) return model.name;
  return `Unknown model (hwType ${hwType})`;
}

/** Battery layout for a hwType, for Device#setEnergy(). */
function batteries(hwType) {
  const model = TAG_MODELS[hwType];
  return (model && model.batteries) || ['CR2450'];
}

module.exports = { TAG_MODELS, modelName, batteries };
